### ISSUE TITLE
ERROR: An error has occurred in Mosey, please report to hippo.:

### ISSUE THREAD

**Issue by rambo1337977** [Hippo/Mosey#1]
java.lang.ClassCastException: com.oracle.truffle.polyglot.PolyglotMap cannot be cast to jdk.nashorn.api.scripting.ScriptObjectMirror
        at rip.hippo.mosey.configuration.impl.JavaScriptConfiguration.<init>(JavaScriptConfiguration.scala:51)
        at rip.hippo.mosey.Main$.main(Main.scala:19)
        at rip.hippo.mosey.Main.main(Main.scala)

**Comment by Hippo** [comment]
That's strange? What version of java are you using to run Mosey?
